signup.get:
    path: /sign-up
    controller: Lithos\Onboarding\SignUpController::getAction
    methods: [GET]
    defaults:
        unsecured: true

signup.post:
    path: /_/sign-up
    controller: Lithos\Onboarding\SignUpController::postAction
    methods: [POST]
    defaults:
        unsecured: true

verify_identity.get:
    path: /verify-identity
    controller: Lithos\Onboarding\VerifyIdentityController::getAction
    methods: [GET]

verify_identity.post:
    path: /_/verify-identity
    controller: Lithos\Onboarding\VerifyIdentityController::postAction
    methods: [POST]

name_team.get:
    path: /name-team
    controller: Lithos\Onboarding\NameTeamController::getAction
    methods: [GET]

name_team.post:
    path: /_/name-team
    controller: Lithos\Onboarding\NameTeamController::postAction
    methods: [POST]

choose_team_url.get:
    path: /choose-team-url
    controller: Lithos\Onboarding\ChooseTeamUrlController::getAction
    methods: [GET]

choose_team_url.post:
    path: /_/choose-team-url
    controller: Lithos\Onboarding\ChooseTeamUrlController::postAction
    methods: [POST]

invite_team.get:
    path: /invite-team
    controller: Lithos\Onboarding\InviteTeamController::getAction
    methods: [GET]

invite_team.post:
    path: /_/invite-team
    controller: Lithos\Onboarding\InviteTeamController::postAction
    methods: [POST]
