signup.get:
    path: /sign-up
    controller: Hipper\Onboarding\SignUpController::getAction
    methods: [GET]
    defaults:
        unsecured: true

signup.post:
    path: /_/sign-up
    controller: Hipper\Onboarding\SignUpController::postAction
    methods: [POST]
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

verify_identity.get:
    path: /verify-identity
    controller: Hipper\Onboarding\VerifyIdentityController::getAction
    methods: [GET]

verify_identity.post:
    path: /_/verify-identity
    controller: Hipper\Onboarding\VerifyIdentityController::postAction
    methods: [POST]
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

name_team.get:
    path: /name-team
    controller: Hipper\Onboarding\NameTeamController::getAction
    methods: [GET]
    defaults:
        _before_middlewares:
            - onboarding_verified_person_middleware:before

name_team.post:
    path: /_/name-team
    controller: Hipper\Onboarding\NameTeamController::postAction
    methods: [POST]
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

choose_team_url.get:
    path: /choose-team-url
    controller: Hipper\Onboarding\ChooseTeamUrlController::getAction
    methods: [GET]
    defaults:
        _before_middlewares:
            - onboarding_verified_person_middleware:before

choose_team_url.post:
    path: /_/choose-team-url
    controller: Hipper\Onboarding\ChooseTeamUrlController::postAction
    methods: [POST]
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

invite.get:
    path: /invite
    controller: Hipper\Onboarding\InviteController::getAction
    methods: [GET]
    defaults:
        _before_middlewares:
            - onboarding_verified_person_middleware:before

invite.post:
    path: /_/invite
    controller: Hipper\Onboarding\InviteController::postAction
    methods: [POST]
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

invite.emails.post:
    path: /_/invite/emails
    controller: Hipper\Onboarding\InviteController::postEmailInvitesAction
    methods: [POST]
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

finalize.get:
    path: /begin
    controller: Hipper\Onboarding\FinalizeController::getAction
    methods: [GET]
    defaults:
        _before_middlewares:
            - onboarding_verified_person_middleware:before
