framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public-roots/assets/public/build/manifest.json'
        base_url: '%env(APP_PROTOCOL)%://%env(ASSET_DOMAIN)%/'

    secret: '%env(APP_SECRET)%'

    session:
        handler_id: ~
        cookie_lifetime: 0
        name: 's'
        cookie_httponly: true

    php_errors:
        log: false
