framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public-roots/assets/public/build/manifest.json'
        base_urls: 
            - 'https://%env(ASSET_DOMAIN)%/'

    secret: '%env(APP_SECRET)%'

    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        storage_id: lithos_session_storage
        cookie_lifetime: 345600
        name: 's'
        cookie_httponly: true
        cookie_secure: true
        cookie_samesite: 'lax'

    php_errors:
        log: false
