framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public-roots/app/public/build/manifest.json'

    secret: '%env(APP_SECRET)%'

    session:
        handler_id: ~
        cookie_lifetime: 0
        name: 's'
        cookie_httponly: true

    php_errors:
        log: false
