parser: "@typescript-eslint/parser"

parserOptions:
    ecmaVersion: 6
    project: './tsconfig.json'

env:
    browser: true

extends:
    - airbnb-typescript/base
    - plugin:@typescript-eslint/recommended

rules:
    array-bracket-spacing: off
    arrow-body-style: off
    arrow-parens: off
    class-methods-use-this: off
    comma-dangle: off
    func-names: off
    indent: off
    lines-between-class-members: off
    max-len:
        - error
        - code: 120
          ignoreRegExpLiterals: true
    no-continue: off
    no-empty:
        - error
        - allowEmptyCatch: true
    no-mixed-operators: off
    no-param-reassign: off
    no-restricted-globals: off
    no-restricted-syntax: off
    no-shadow: off
    no-underscore-dangle: off
    object-curly-newline: off
    object-shorthand: off
    operator-assignment: off
    operator-linebreak: off
    prefer-destructuring: off
    prefer-object-spread: off
    prefer-template: off
    yoda: off
    "@typescript-eslint/no-use-before-define":
        - error
        - functions: false
    "@typescript-eslint/consistent-type-assertions": off
    "@typescript-eslint/indent": [error, 4]
    "@typescript-eslint/member-delimiter-style": off
    "@typescript-eslint/no-inferrable-types":
        - error
        - ignoreParameters: true
          ignoreProperties: true
    "@typescript-eslint/no-explicit-any": off
    "@typescript-eslint/no-unused-vars":
        - error
        - args: none
    "@typescript-eslint/lines-between-class-members": off
    "@typescript-eslint/camelcase": off
    "@typescript-eslint/ban-types": off
    "@typescript-eslint/explicit-module-boundary-types": off
    "@typescript-eslint/comma-dangle":
        - error
        - arrays: always-multiline
          objects: always-multiline
          imports: always-multiline
          exports: always-multiline
          enums: always-multiline
          generics: always-multiline
          tuples: always-multiline
          functions: ignore

settings:
    import/resolver:
        node:
            extensions: ['.ts']
            moduleDirectory: ['node_modules', 'src/ts/']
