version: '3'
services:
  nginx:
    build: "config/docker/web"
    ports:
        - "443:443"
    volumes:
        - .:/var/hipper
    links:
        - php
  node:
    build: "config/docker/node"
    volumes:
        - .:/var/hipper
  php:
    build: "config/docker/php"
    tty: true
    ports:
        - "9000:9000"
    volumes:
        - .:/var/hipper
    links:
        - postgres
  postgres:
    build: "config/docker/db"
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=hipper
    ports:
        - "5432:5432"
    volumes:
        - ~/docker/volumes/postgres:/var/lib/postgresql/data
        - ./sql:/var/sql
