index:
    path: /
    controller: hleo\Controller\DefaultController::index

signup:
    path: /sign-up
    controller: hleo\Controller\SignupController::getAction
    methods: [GET]

signup_post:
    path: /sign-up
    controller: hleo\Controller\SignupController::postAction
    methods: [POST]

verify_email:
    path: /m/verify-email
    controller: hleo\Controller\VerifyEmailController::getAction
