index:
    path: /
    controller: hleo\Controller\DefaultController::index

signup:
    path: /signup
    controller: hleo\Controller\SignupController::index
    methods: [GET]

signup_post:
    path: /signup
    controller: hleo\Controller\SignupController::post
    methods: [POST]

verify_email:
    path: /m/verify-email
    controller: hleo\Controller\VerifyEmailController::getAction
