index:
    path: /
    controller: hleo\Controller\DefaultController::index

signup:
    path: /signup
    controller: hleo\Controller\SignupController::index

register:
    path: /register
    controller: hleo\Controller\RegistrationController::post

verify_email:
    path: /m/verify-email
    controller: hleo\Controller\VerifyEmailController::getAction
