---
- name: Create var directory
  file:
      path: /var/hipper/var
      state: directory
      recurse: yes
      owner: www-data
      group: sysadmin
      mode: '755'

- name: Clear cache
  become: yes
  become_user: www-data
  command: php bin/console cache:clear
  args:
      chdir: /var/hipper

- name: Remove cached environment variables file
  file:
      path: /var/hipper/.env.local.php
      state: absent

- name: Dump cached environment variables file
  command: php bin/console app:dump-combined-env-config prod
  args:
      chdir: /var/hipper

- name: Set owner of cached environment variables file
  file:
      path: /var/hipper/.env.local.php
      owner: www-data
      group: sysadmin
      mode: '755'

- name: Warm-up cache
  become: yes
  become_user: www-data
  command: php bin/console cache:warmup
  args:
      chdir: /var/hipper

- name: Set path to PHP preload file
  lineinfile: dest=/etc/php/7.4/fpm/php.ini regexp="^[#|;]?opcache.preload =" insertafter="^[#|;]?opcache.preload =" line="opcache.preload = {{ php_preload_file }}"
  notify: restart php-fpm

- name: Set PHP preload user
  lineinfile: dest=/etc/php/7.4/fpm/php.ini regexp="^[#|;]?opcache.preload_user =" insertafter="^[#|;]?opcache.preload_user =" line="opcache.preload_user = www-data"
  notify: restart php-fpm
