api.sign_up_flow.signup:
    path: /_/sign-up
    controller: Hipper\Api\SignUpFlow\Controller\SignUpController::postAction
    methods: [POST]
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

api.sign_up_flow.verify_identity:
    path: /_/sign-up/verify-email-address
    controller: Hipper\Api\SignUpFlow\Controller\VerifyEmailAddressController::postAction
    methods: [POST]
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

api.sign_up_flow.name_organization:
    path: /_/sign-up/name-organization
    controller: Hipper\Api\SignUpFlow\Controller\NameOrganizationController::postAction
    methods: [POST]
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

api.sign_up_flow.choose_organization_url:
    path: /_/sign-up/choose-organization-url
    controller: Hipper\Api\SignUpFlow\Controller\ChooseOrganizationUrlController::postAction
    methods: [POST]
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

api.sign_up_flow.invite:
    path: /_/invite
    controller: Hipper\Api\SignUpFlow\Controller\InviteController::postAction
    methods: [POST]
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

api.sign_up_flow.invite_by_email:
    path: /_/invite/emails
    controller: Hipper\Api\SignUpFlow\Controller\InviteController::postEmailInvitesAction
    methods: [POST]
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before
