FROM php:7.3-fpm
MAINTAINER Matt Arnold (typeof.developer@gmail.com)
RUN apt-get update
RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql
RUN docker-php-ext-install bcmath
