join.post:
    path: /_/join
    methods: [POST]
    controller: Hipper\Api\App\Controller\Organization\JoinController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

join_by_invitation.post:
    path: /_/join/by-invitation
    methods: [POST]
    controller: Hipper\Api\App\Controller\Organization\JoinByInvitationController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before
