tokenized_login.get:
    path: /tokenized-login
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Organization\TokenizedLoginController::getAction
    defaults:
        unsecured: true

login.post:
    path: /_/login
    methods: [POST]
    controller: Hipper\Api\App\Controller\Organization\LoginController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before
