document_routes:
    resource: document.yml

join_routes:
    resource: join.yml

login_routes:
    resource: login.yml

project_routes:
    resource: project.yml

section_routes:
     resource: section.yml

team_routes:
    resource: team.yml

index:
    path: /
    controller: Hipper\Controller\DefaultController::index
    defaults:
        _before_middlewares:
            - app_onboarding_completed_middleware:before

welcome.get:
    path: /welcome
    methods: [GET]
    controller: Hipper\App\WelcomeController::getAction
