index:
    path: /
    controller: Lithos\Controller\DefaultController::index
    defaults:
        _before_middlewares:
            - app_onboarding_completed_middleware:before

tokenized_login.get:
    path: /tokenized-login
    methods: [GET]
    controller: Lithos\App\TokenizedLoginController::getAction
    defaults:
        unsecured: true

login.post:
    path: /_/login
    methods: [POST]
    controller: Lithos\App\LoginController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

join.post:
    path: /_/join
    methods: [POST]
    controller: Lithos\App\JoinOrganizationController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

join_by_invitation.get:
    path: /join/by-invitation
    methods: [GET]
    controller: Lithos\App\JoinByInvitationController::getAction
    defaults:
        unsecured: true

join_by_invitation.post:
    path: /_/join/by-invitation
    methods: [POST]
    controller: Lithos\App\JoinByInvitationController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

welcome.get:
    path: /welcome
    methods: [GET]
    controller: Lithos\App\WelcomeController::getAction

create_team.post:
    path: /_/create-team
    methods: [POST]
    controller: Lithos\App\CreateTeamController::postAction
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before
