index:
    path: /
    controller: Lithos\Controller\DefaultController::index
    defaults:
        _before_middlewares:
            - app_onboarding_completed_middleware:before

tokenized_login.get:
    path: /tokenized-login
    methods: [GET]
    controller: Lithos\App\TokenizedLoginController::getAction
    defaults:
        unsecured: true

login.post:
    path: /_/login
    methods: [POST]
    controller: Lithos\App\LoginController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

join.post:
    path: /_/join
    methods: [POST]
    controller: Lithos\App\JoinOrganizationController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

join_by_invitation.get:
    path: /join/by-invitation
    methods: [GET]
    controller: Lithos\App\JoinByInvitationController::getAction
    defaults:
        unsecured: true

join_by_invitation.post:
    path: /_/join/by-invitation
    methods: [POST]
    controller: Lithos\App\JoinByInvitationController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

welcome.get:
    path: /welcome
    methods: [GET]
    controller: Lithos\App\WelcomeController::getAction

create_team.get:
    path: /teams/new
    methods: [GET]
    controller: Lithos\App\Team\CreateTeamController::getAction

create_team_suggest_description.post:
    path: /_/suggest-team-description
    methods: [POST]
    controller: Lithos\App\Team\CreateTeamController::suggestAction
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

create_team.post:
    path: /_/create-team
    methods: [POST]
    controller: Lithos\App\Team\CreateTeamController::postAction
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

team.get:
    path: /team/{url_id}
    methods: [GET]
    controller: Lithos\App\Team\TeamController::getAction
    defaults:
        _before_middlewares:
            - team_model_from_url_id_middleware:before

team_docs.get:
    path: /team/{url_id}/docs
    methods: [GET]
    controller: Lithos\App\Team\TeamDocsController::getAction
    defaults:
        _before_middlewares:
            - team_model_from_url_id_middleware:before
