create_team.get:
    path: /teams/new
    methods: [GET]
    controller: Hipper\App\Team\CreateTeamController::getAction

create_team_suggest_description.post:
    path: /_/suggest-team-description
    methods: [POST]
    controller: Hipper\App\Team\CreateTeamController::suggestAction
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

create_team.post:
    path: /_/create-team
    methods: [POST]
    controller: Hipper\App\Team\CreateTeamController::postAction
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

team.get:
    path: /team/{team_url_id}
    methods: [GET]
    controller: Hipper\App\Team\TeamController::getAction
    defaults:
        _before_middlewares:
            - team_model_from_url_id_middleware:before

team_docs.get:
    path: /team/{team_url_id}/docs
    methods: [GET]
    controller: Hipper\App\Team\TeamDocsController::getAction
    defaults:
        _before_middlewares:
            - team_model_from_url_id_middleware:before

create_team_section.get:
    path: /team/{team_url_id}/docs/new-section
    methods: [GET]
    controller: Hipper\App\Section\CreateSectionController::getAction
    defaults:
        knowledgebase_type: 'team'
        _before_middlewares:
            - team_model_from_url_id_middleware:before

team_docs_new.get:
    path: /team/{team_url_id}/docs/new
    methods: [GET]
    controller: Hipper\App\Document\CreateDocumentController::getAction
    defaults:
        knowledgebase_type: 'team'
        _before_middlewares:
            - team_model_from_url_id_middleware:before

team_doc.get:
    path: /team/{team_url_id}/docs/{path}
    methods: [GET]
    controller: Hipper\App\DocumentOrSectionControllerRouter::route
    defaults:
        knowledgebase_type: 'team'
        action: 'getAction'
        _before_middlewares:
            - team_model_from_url_id_middleware:before
            - knowledgebase_routing_middleware:before
    requirements:
        route: '.+'
