organization.login:
    path: /login
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Organization\LoginController::getAction
    defaults:
        unsecured: true

organization.tokenized_login:
    path: /tokenized-login
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Organization\TokenizedLoginController::getAction
    defaults:
        unsecured: true

organization.sign_out:
    path: /sign-out
    methods: [POST]
    controller: Hipper\FrontEnd\App\Controller\Organization\SignOutController::signOut

organization.search:
    path: /search
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Organization\OrganizationSearchController::getAction

organization.people.search:
    path: /search/people
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Organization\OrganizationPeopleSearchController::getAction

organization.teams.search:
    path: /search/teams
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Organization\OrganizationTeamsSearchController::getAction
