projects.show:
    path: /projects
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Project\ProjectsController::getAction

project.create:
    path: /projects/new
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Project\CreateProjectController::getAction

project.show:
    path: /projects/{project_url_id}
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Project\ProjectController::getAction
    defaults:
        _before_middlewares:
            - project_model_from_url_id_middleware:before

project.docs.list:
    path: /projects/{project_url_id}/docs
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Project\ProjectDocsController::getAction
    defaults:
        _before_middlewares:
            - project_model_from_url_id_middleware:before

project.section.create:
    path: /projects/{project_url_id}/docs/new-section
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Section\CreateSectionController::getAction
    defaults:
        knowledgebase_type: 'project'
        _before_middlewares:
            - project_model_from_url_id_middleware:before

project.doc.create:
    path: /projects/{project_url_id}/docs/new
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Document\CreateDocumentController::getAction
    defaults:
        knowledgebase_type: 'project'
        _before_middlewares:
            - project_model_from_url_id_middleware:before

project.doc.show:
    path: /projects/{project_url_id}/docs/{path}
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Knowledgebase\DocumentOrSectionControllerRouter::route
    defaults:
        knowledgebase_type: 'project'
        action: 'getAction'
        _before_middlewares:
            - project_model_from_url_id_middleware:before
            - knowledgebase_routing_middleware:before
    requirements:
        route: '.+'
