person_routes:
    resource: person.yml
    name_prefix: 'front_end.app.'

project_routes:
    resource: project.yml
    name_prefix: 'front_end.app.'

team_routes:
    resource: team.yml
    name_prefix: 'front_end.app.'

organization_routes:
    resource: organization.yml
    name_prefix: 'front_end.app.'

front_end.app.welcome.get:
    path: /welcome
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\WelcomeController::getAction
