teams.list:
    path: /teams
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Team\TeamsController::getAction

team.create:
    path: /teams/new
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Team\CreateTeamController::getAction

team.show:
    path: /teams/{team_url_id}
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Team\TeamController::getAction
    defaults:
        _before_middlewares:
            - team_model_from_url_id_middleware:before

team.docs.list:
    path: /teams/{team_url_id}/docs
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Team\TeamDocsController::getAction
    defaults:
        _before_middlewares:
            - team_model_from_url_id_middleware:before

team.section.create:
    path: /teams/{team_url_id}/docs/new-section
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Section\CreateSectionController::getAction
    defaults:
        knowledgebase_type: 'team'
        _before_middlewares:
            - team_model_from_url_id_middleware:before

team.doc.create:
    path: /teams/{team_url_id}/docs/new
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Document\CreateDocumentController::getAction
    defaults:
        knowledgebase_type: 'team'
        _before_middlewares:
            - team_model_from_url_id_middleware:before

team.doc.edit:
    path: /teams/{team_url_id}/docs/edit/{path}
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Document\EditDocumentController::getAction
    defaults:
        knowledgebase_type: 'team'
        _before_middlewares:
            - team_model_from_url_id_middleware:before
            - knowledgebase_routing_middleware:before
    requirements:
        path: '.+'

team.doc.export:
    path: /teams/{team_url_id}/docs/export/{path}
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Document\ExportDocumentController::getAction
    defaults:
        knowledgebase_type: 'team'
        _before_middlewares:
            - team_model_from_url_id_middleware:before
            - knowledgebase_routing_middleware:before
    requirements:
        path: '.+'

team.doc.show:
    path: /teams/{team_url_id}/docs/{path}
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Knowledgebase\DocumentOrSectionControllerRouter::route
    defaults:
        knowledgebase_type: 'team'
        action: 'getAction'
        _before_middlewares:
            - team_model_from_url_id_middleware:before
            - knowledgebase_routing_middleware:before
    requirements:
        path: '.+'

team.search:
    path: /teams/{team_url_id}/search
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Team\TeamSearchController::getAction
    defaults:
        _before_middlewares:
            - team_model_from_url_id_middleware:before

team.members.search:
    path: /teams/{team_url_id}/search/members
    methods: [GET]
    controller: Hipper\FrontEnd\App\Controller\Team\TeamMembersSearchController::getAction
    defaults:
        _before_middlewares:
            - team_model_from_url_id_middleware:before
