organization.join:
    path: /_/join
    methods: [POST]
    controller: Hipper\Api\App\Controller\Organization\JoinController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

organization.join_by_invitation:
    path: /_/join/by-invitation
    methods: [POST]
    controller: Hipper\Api\App\Controller\Organization\JoinByInvitationController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

organization.login:
    path: /_/login
    methods: [POST]
    controller: Hipper\Api\App\Controller\Organization\LoginController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

organization.search:
    path: /_/search
    methods: [GET]
    controller: Hipper\Api\App\Controller\Organization\OrganizationSearchController::getAction

organization.teams.search:
    path: /_/search/teams
    methods: [GET]
    controller: Hipper\Api\App\Controller\Organization\OrganizationTeamsSearchController::getAction
