organization.join:
    path: /_/join
    methods: [POST]
    controller: Hipper\Api\App\Controller\Organization\Join\JoinOrganizationController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

organization.join.verify_email_address:
    path: /_/join/verify-email-address
    methods: [POST]
    controller: Hipper\Api\App\Controller\Organization\Join\VerifyEmailAddressController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

organization.join_by_invitation:
    path: /_/join/by-invitation
    methods: [POST]
    controller: Hipper\Api\App\Controller\Organization\Join\JoinByInvitationController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

organization.login:
    path: /_/login
    methods: [POST]
    controller: Hipper\Api\App\Controller\Organization\LoginController::postAction
    defaults:
        unsecured: true
        _before_middlewares:
            - require_json_content_type_middleware:before

organization.search:
    path: /_/search
    methods: [GET]
    controller: Hipper\Api\App\Controller\Organization\OrganizationSearchController::getAction

organization.people.search:
    path: /_/search/people
    methods: [GET]
    controller: Hipper\Api\App\Controller\Organization\OrganizationPeopleSearchController::getAction

organization.projects.search:
    path: /_/search/projects
    methods: [GET]
    controller: Hipper\Api\App\Controller\Organization\OrganizationProjectsSearchController::getAction

organization.teams.search:
    path: /_/search/teams
    methods: [GET]
    controller: Hipper\Api\App\Controller\Organization\OrganizationTeamsSearchController::getAction

organization.request_knowledge_export:
    path: /_/request-knowledge-export
    methods: [POST]
    controller: Hipper\Api\App\Controller\Organization\ExportOrganizationKnowledgeController::postAction
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before
