project.create:
    path: /_/create-project
    methods: [POST]
    controller: Hipper\Api\App\Controller\Project\CreateProjectController::postAction
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

project.search:
    path: /_/projects/{project_url_id}/search
    methods: [GET]
    controller: Hipper\Api\App\Controller\Project\ProjectSearchController::getAction
    defaults:
        _before_middlewares:
            - project_model_from_url_id_middleware:before

project.members.search:
    path: /_/projects/{project_url_id}/search/members
    methods: [GET]
    controller: Hipper\Api\App\Controller\Project\ProjectMembersSearchController::getAction
    defaults:
        _before_middlewares:
            - project_model_from_url_id_middleware:before
