team.suggest_description:
    path: /_/suggest-team-description
    methods: [POST]
    controller: Hipper\Api\App\Controller\Team\SuggestTeamDescriptionController::postAction
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

team.create:
    path: /_/create-team
    methods: [POST]
    controller: Hipper\Api\App\Controller\Team\CreateTeamController::postAction
    defaults:
        _before_middlewares:
            - require_json_content_type_middleware:before

team.search:
    path: /_/teams/{team_url_id}/search
    methods: [GET]
    controller: Hipper\Api\App\Controller\Team\TeamSearchController::getAction
    defaults:
        _before_middlewares:
            - team_model_from_url_id_middleware:before

team.members.search:
    path: /_/teams/{team_url_id}/members/search
    methods: [GET]
    controller: Hipper\Api\App\Controller\Team\TeamMembersSearchController::getAction
    defaults:
        _before_middlewares:
            - team_model_from_url_id_middleware:before
