front_end.sign_up_flow.signup:
    path: /sign-up
    controller: Hipper\FrontEnd\SignUpFlow\Controller\SignUpController::getAction
    methods: [GET]
    defaults:
        unsecured: true

front_end.sign_up_flow.verify_email_address:
    path: /sign-up/verify-email-address
    controller: Hipper\FrontEnd\SignUpFlow\Controller\VerifyEmailAddressController::getAction
    methods: [GET]
    defaults:
        unsecured: true

front_end.sign_up_flow.choose_organization_url:
    path: /sign-up/choose-organization-url
    controller: Hipper\FrontEnd\SignUpFlow\Controller\ChooseOrganizationUrlController::getAction
    methods: [GET]

front_end.sign_up_flow.invite:
    path: /sign-up/invite
    controller: Hipper\FrontEnd\SignUpFlow\Controller\InviteController::getAction
    methods: [GET]

front_end.sign_up_flow.finalize:
    path: /sign-up/begin
    controller: Hipper\FrontEnd\SignUpFlow\Controller\FinalizeController::getAction
    methods: [GET]
